import XCTest
@testable import Clipd

final class PrivacyFilterTests: XCTestCase {

    func testTransientRejected() {
        XCTAssertEqual(
            PrivacyFilter().rejection(forMarkers: [PrivacyFilter.transientType]),
            .transient
        )
    }

    func testAutoGeneratedRejected() {
        XCTAssertEqual(
            PrivacyFilter().rejection(forMarkers: [PrivacyFilter.autoGeneratedType]),
            .autoGenerated
        )
    }

    func testConcealedRejectedByDefault() {
        XCTAssertEqual(
            PrivacyFilter().rejection(forMarkers: [PrivacyFilter.concealedType]),
            .concealed
        )
    }

    func testConcealedAllowedWhenMasked() {
        XCTAssertNil(
            PrivacyFilter(storeConcealedMasked: true)
                .rejection(forMarkers: [PrivacyFilter.concealedType])
        )
    }

    func testNoMarkersAllowed() {
        XCTAssertNil(PrivacyFilter().rejection(forMarkers: []))
        XCTAssertNil(PrivacyFilter().rejection(forMarkers: ["public.utf8-plain-text"]))
    }

    func testTransientStillRejectsEvenWhenConcealedMaskingOn() {
        let filter = PrivacyFilter(storeConcealedMasked: true)
        XCTAssertEqual(
            filter.rejection(forMarkers: [PrivacyFilter.transientType, PrivacyFilter.concealedType]),
            .transient
        )
    }
}
