import Foundation

/// 条目被拒绝入库的原因。
public enum RejectReason: String, Sendable, Equatable {
    case concealed       // org.nspasteboard.ConcealedType(密码管理器)
    case transient       // org.nspasteboard.TransientType
    case autoGenerated   // org.nspasteboard.AutoGeneratedType
    case selfWrite       // 自身写回
    case empty           // 无可用负载
}

/// 隐私过滤:仅依据 `org.nspasteboard.*` 标记判定,**不读取负载字节**。
///
/// 这样密码类内容在被拒绝的路径上永不进入进程内存。
public struct PrivacyFilter: Sendable {
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let transientType = "org.nspasteboard.TransientType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"

    /// 命中 ConcealedType 时是否仍允许(交由上层遮蔽存储)。默认 false=拒绝。
    public let storeConcealedMasked: Bool

    public init(storeConcealedMasked: Bool = false) {
        self.storeConcealedMasked = storeConcealedMasked
    }

    /// 返回拒绝原因;nil 表示允许捕获。
    public func rejection(forMarkers markers: Set<String>) -> RejectReason? {
        if markers.contains(Self.transientType) { return .transient }
        if markers.contains(Self.autoGeneratedType) { return .autoGenerated }
        if markers.contains(Self.concealedType) {
            return storeConcealedMasked ? nil : .concealed
        }
        return nil
    }
}
